[package]
name = "totp-clipboard"
version = "0.1.0"
authors = ["Guillaume Gauvrit <guillaume@gauvr.it>"]

[dependencies]

log = "^0.4"
pretty_env_logger = "^0.2"

libreauth = "^0.8.0"
clipboard = "^0.4.6"
serde_json = "^1.0"
libappindicator = "^0.3.0"
